<a href="https://colab.research.google.com/github/Jayameena832/Interest-Level-estimation/blob/main/Copy_of_Genres.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/content  rating with string.csv')

In [ ]:
# printing the first 5 rows of the dataframe
movies_data.head(10)

content_rating
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN

In [ ]:
# number of rows and columns in the data frame

movies_data.shape

(600, 1)

In [ ]:
selected_features = ['content_rating']
print(selected_features)

['content_rating']


In [ ]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
combined_features = movies_data['content_rating']

In [ ]:
print(combined_features)

0        
1        
2        
3        
4        
       ..
595      
596    PG
597     R
598      
599    PG
Name: content_rating, Length: 600, dtype: object


In [ ]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (27, 0)	1.0
  (36, 0)	1.0
  (49, 0)	1.0
  (53, 0)	1.0
  (68, 0)	1.0
  (83, 0)	1.0
  (104, 0)	1.0
  (111, 0)	1.0
  (132, 0)	1.0
  (133, 0)	1.0
  (137, 0)	1.0
  (138, 0)	1.0
  (140, 0)	1.0
  (142, 0)	1.0
  (154, 0)	1.0
  (155, 0)	1.0
  (164, 0)	1.0
  (169, 0)	1.0
  (171, 0)	1.0
  (173, 0)	1.0
  (175, 0)	1.0
  (178, 0)	1.0
  (179, 0)	1.0
  (182, 0)	1.0
  (186, 0)	1.0
  :	:
  (546, 0)	1.0
  (547, 0)	1.0
  (549, 0)	1.0
  (553, 0)	1.0
  (555, 0)	1.0
  (557, 0)	1.0
  (563, 0)	1.0
  (567, 0)	1.0
  (571, 0)	1.0
  (573, 0)	1.0
  (575, 0)	1.0
  (576, 0)	1.0
  (578, 0)	1.0
  (579, 0)	1.0
  (580, 0)	1.0
  (583, 0)	1.0
  (584, 0)	1.0
  (585, 0)	1.0
  (586, 0)	1.0
  (587, 0)	1.0
  (591, 0)	1.0
  (593, 0)	1.0
  (594, 0)	1.0
  (596, 0)	1.0
  (599, 0)	1.0


Cosine Similarity

In [ ]:
pd.DataFrame(feature_vectors).to_csv("x_train_smote_oversample.csv")

In [ ]:
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
print(similarity.shape)

(600, 600)


In [ ]:
pd.DataFrame(similarity).to_csv("Similarity.csv")